name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  runner-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Print machine information
      run: uname -a

    - name: Check Node.js and npm versions
      run: |
        node -v
        npm -v

    - name: Run tests
      run: npm test --if-present

    - name: Run build
      run: npm run build --if-present

    # הצעד החדש של Stage 6:
    - name: Verify Docker Execution
      run: docker --version